spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;MODE=MSSQLServer
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

logging:
  level:
    root: info
