spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MSSQLServer
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always